"""iso-origin.py: the three Where we come from scenes, 2026-10-02 (the
founder's five fixes). True isometric, 30 degree axes, as the card
illustrations (Illustrations.jsx): a point (x, y, z) lands at
((x - y) cos 30, (x + y) sin 30 - z). Boxes are painted back to front; for a
box the visible faces are the top (iso-t), the face at y = y1 (iso-l) and
the face at x = x1 (iso-r). Each scene is fitted as the cards are: its
binding side to 112px (224 units on the 280 drawing), centred horizontally,
its lowest point on the shared baseline 14px above the floor (252 units).

Writes src/components/story/OriginScenes.jsx. Run: python .measure/iso-origin.py
"""
import math, os

C, S = math.cos(math.radians(30)), 0.5
def P(x, y, z):
    return ((x - y) * C, (x + y) * S - z)

def box(x0, y0, z0, dx, dy, dz, top='iso-t'):
    x1, y1, z1 = x0 + dx, y0 + dy, z0 + dz
    return [
        ('iso-l', [(x0, y1, z0), (x1, y1, z0), (x1, y1, z1), (x0, y1, z1)]),
        ('iso-r', [(x1, y0, z0), (x1, y1, z0), (x1, y1, z1), (x1, y0, z1)]),
        (top, [(x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)]),
    ], x0 + y0 + dx + dy

def face_l(x0, x1, y, z0, z1, cls):
    """A rectangle on a y = const face (the left, front face)."""
    return (cls, [(x0, y, z0), (x1, y, z0), (x1, y, z1), (x0, y, z1)])

def scene(items, lines=(), dots=()):
    """items: list of (depth, [faces]) painted by depth; lines and dots in 3D."""
    polys = []
    for _, faces in sorted(items, key=lambda t: t[0]):
        polys.extend(faces)
    pts = [P(*p) for _, f in polys for p in f]
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    w, h = max(xs) - min(xs), max(ys) - min(ys)
    k = min(224 / w, 224 / h)
    ox = 140 - (min(xs) + w / 2) * k
    oy = 252 - max(ys) * k
    T = lambda p: (round(P(*p)[0] * k + ox, 1), round(P(*p)[1] * k + oy, 1))
    out = []
    for cls, f in polys:
        d = 'M' + ' L'.join(f'{a} {b}' for a, b in map(T, f)) + 'Z'
        out.append(f'<path className="{cls}" d="{d}" />')
    for a, b in lines:
        (x1, y1), (x2, y2) = T(a), T(b)
        out.append(f'<path className="iso-arc" d="M{x1} {y1} L{x2} {y2}" />')
    for p in dots:
        x, y = T(p)
        out.append(f'<circle className="iso-dot" cx="{x}" cy="{y}" r="{round(4 * k, 1)}" />')
    return out

# 01: one ad panel standing alone: a slab 64 wide, 10 deep, 84 tall, an
# image block and a button on its front face (no lines standing for text:
# BUILD-LAW, Real over drawn).
def ad(x, y):
    faces, depth = box(x, y, 0, 64, 10, 84)
    yf = y + 10
    faces = faces + [
        face_l(x + 8, x + 56, yf, 34, 76, 'iso-t'),
        face_l(x + 8, x + 36, yf, 12, 24, 'iso-d'),
    ]
    return (depth, faces)

s1 = scene([ad(0, 0)])

# 02: the ad panel beside a page: the page a slab 72 wide, 10 deep, 104
# tall, a header bar, two form fields and a button on its face.
def page(x, y):
    faces, depth = box(x, y, 0, 72, 10, 104)
    yf = y + 10
    faces = faces + [
        face_l(x + 8, x + 64, yf, 88, 96, 'iso-r'),
        face_l(x + 8, x + 64, yf, 62, 76, 'iso-t'),
        face_l(x + 8, x + 64, yf, 42, 56, 'iso-t'),
        face_l(x + 8, x + 40, yf, 18, 32, 'iso-d'),
    ]
    return (depth, faces)

s2 = scene([ad(0, 40), page(96, 40)])

# 03: four flat tiles, 60 x 60 x 10, in a square, joined along their tops by
# connectors with a dot at each centre; the front tile's top is yellow.
tiles = []
for (tx, ty) in [(0, 0), (84, 0), (0, 84), (84, 84)]:
    top = 'iso-y' if (tx, ty) == (84, 84) else 'iso-t'
    faces, depth = box(tx, ty, 0, 60, 60, 10, top)
    tiles.append((depth, faces))
c = lambda tx, ty: (tx + 30, ty + 30, 10)
links = [(c(0, 0), c(84, 0)), (c(84, 0), c(84, 84)), (c(84, 84), c(0, 84)), (c(0, 84), c(0, 0))]
s3 = scene(tiles, links, [c(0, 0), c(84, 0), c(0, 84), c(84, 84)])

def comp(name, body):
    inner = '\n      '.join(body)
    return f'''export function {name}({{ className }}) {{
  return (
    <svg className={{className}} viewBox="0 0 280 280" width="140" height="140" aria-hidden="true" focusable="false">
      {inner}
    </svg>
  );
}}
'''

head = '''import React from 'react';

/* WHERE WE COME FROM, DRAWN (the founder's five fixes, 2026-10-02). Three
   new isometric scenes in the hand of the card illustrations
   (Illustrations.jsx): true isometric on 30 degree axes, an asphalt 1.5px
   keyline with round joins, faces TOP white, LEFT cream, RIGHT bone (the
   light palette, on a cream tile), connectors 2px with an asphalt dot at
   each join, each fitted to 112px with its foot on the shared baseline 14px
   above the floor. GENERATED by .measure/iso-origin.py; change the script,
   not this file.

     OriginAds     01: one ad panel standing alone, an image block and a
                   button on its face
     OriginPage    02: the ad panel beside a page with a header, two form
                   fields and a button
     OriginSystem  03: four flat tiles joined by connectors, the fourth
                   (the front one) yellow, the scene's one yellow

   Decorative: each stop's title says what the scene is. */
'''
src = head + '\n' + comp('OriginAds', s1) + '\n' + comp('OriginPage', s2) + '\n' + comp('OriginSystem', s3)
here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, '..', 'src', 'components', 'story', 'OriginScenes.jsx'), 'w', encoding='utf8', newline='\n') as f:
    f.write(src)
print('ok', len(s1), len(s2), len(s3))
