import React from 'react';

/* THE CARD ILLUSTRATIONS, 2026-09-24 (the founder's illustration pass; the
   isometric outline style of coinsetters.io's services section, translated
   to this palette). They are the card's artwork on home's What we do and
   About's What we build it around.

   TRUE ISOMETRIC, 30 degree axes: a point (x, y, z) lands at
   (x - y) * cos 30, (x + y) * sin 30 - z. The geometry is generated, not
   hand-placed, so the light is the same on all four: TOP lit-raised, LEFT
   lit-near, RIGHT steel-dark. The keyline is bone at 1.5px with round joins,
   the sound arcs and connectors 2px (ArtCard.css).

   THE SECOND ITERATION, later on 2026-09-24 (the founder): the objects float
   - no base plates, no shadows - and each is scaled so its larger dimension
   fills 124px of the 140px slot, centred. Each has exactly one yellow
   element:

     Branding     a stamp block with a raised V on its top face (kept); the V
     Websites     a browser lying flat like a tablet, 3:2, three dots, a wide
                  bar, a narrow bar; the block
     Marketing    a megaphone, a small cylinder widening to an open elliptical
                  mouth, angled 30 degrees up the iso axis, the handle under
                  it, three sound arcs; the middle arc
     Automation   three 32-unit cubes on the iso axis with 12-unit gaps,
                  joined along their top edges by connectors with a dot at
                  each join; the last cube

   THE THIRD ITERATION, 2026-09-24 (the founder's energy pass): the cards
   are cream now, so the palette is the light one - an asphalt keyline at
   1.5px, TOP white, LEFT cream, RIGHT bone - and each object carries one
   arc blue element beside its yellow one:

     Branding     the yellow V; a blue base edge (an 8-unit slab under the block)
     Websites     the yellow block; the blue top bar, its three dots white
     Marketing    the yellow middle arc; a blue band round the horn
     Automation   the yellow last cube; the blue connectors and their dots

   Arc blue appears here and on the Plan Builder's progress dots, nowhere
   else. Generated by iso3.py (the scratchpad of that session).

   THE LAUNCH BATCH, 2026-09-25 (the founder), supersedes the normalising
   above and every note on the objects before it where they differ:
     - every object fits inside 112 x 112 EXACTLY, scaled by its binding
       side (all four are width-bound: 112.0px wide), centred horizontally,
       its lowest point on one baseline 14px above the box floor. The four
       feet, measured from the box top: 126.0, 126.0, 126.0, 126.0px.
     - Websites is a 4:3 window LEANING BACK 45 degrees. Flat, a window
       projects at 1.6:1 whatever its proportion, and upright at 0.72:1;
       leaning back it projects square and fills the box. Its blue bar is a
       strip about 6px deep.
     - Marketing's three arcs are shorter and closer in, and the horn body
       is white. Its blue band is a 2px ring round the horn (its near half),
       because a filled band showed its whole section, 400px2 and more,
       against the yellow arc's 90.
     - EQUAL ACCENT, measured on the rendered SVG, yellow against blue:
       Branding 488 / 493px2, Websites 293 / 298, Marketing 91 / 93,
       Automation 1659 / 1391 (its blue is now the FIRST CUBE, the same size
       as the yellow last cube, partly behind the middle one; the connectors
       were a 2px line against a cube and could not be made equal, and are
       keylines now).
   Generated by iso5.py, measured by acc.py.

   THREE COLOURS, 2026-09-25 (the founder): no blue. Each object keeps one
   yellow element and nothing else in colour. Branding's blue base edge is
   the block's own faces; Websites' blue strip is white, its three dots
   asphalt; Marketing's blue ring is an asphalt 2px ring; Automation's blue
   first cube is a white cube like the middle one. The equal-accent pairs
   above are history. Generated by iso6.py. Websites' strip is its own class
   (`iso-w`, solid white in both palettes) since the colours came back
   without the blue (2026-09-25): iso7.py.

   Decorative: the card's title says what each one is. */

export function IsoBranding({ className }) {
  return (
    <svg className={className} viewBox="0 0 280 280" width="140" height="140" aria-hidden="true" focusable="false">
      <path className="iso-l" d="M28.0 187.3 L140.0 252.0 L140.0 239.1 L28.0 174.4Z" />
      <path className="iso-r" d="M252.0 187.3 L140.0 252.0 L140.0 239.1 L252.0 174.4Z" />
      <path className="iso-l" d="M28.0 174.4 L140.0 239.1 L140.0 197.9 L28.0 133.3Z" />
      <path className="iso-r" d="M252.0 174.4 L140.0 239.1 L140.0 197.9 L252.0 133.3Z" />
      <path className="iso-t" d="M140.0 68.6 L252.0 133.3 L140.0 197.9 L28.0 133.3Z" />
      <path className="iso-l" d="M116.6 157.4 L98.3 146.8 L98.3 136.2 L116.6 146.8Z" />
      <path className="iso-r" d="M205.2 135.6 L116.6 157.4 L116.6 146.8 L205.2 125.0Z" />
      <path className="iso-l" d="M98.3 146.8 L135.9 95.6 L135.9 85.1 L98.3 136.2Z" />
      <path className="iso-y" d="M135.9 85.1 L154.3 95.6 L131.9 127.4 L186.8 114.4 L205.2 125.0 L116.6 146.8 L98.3 136.2Z" />
    </svg>
  );
}

export function IsoWebsites({ className }) {
  return (
    <svg className={className} viewBox="0 0 280 280" width="140" height="140" aria-hidden="true" focusable="false">
      <path className="iso-r" d="M176.1 252.0 L252.0 120.6 L246.9 117.7 L171.1 249.1Z" />
      <path className="iso-t" d="M108.9 38.0 L252.0 120.6 L246.9 117.7 L103.9 35.1Z" />
      <path className="iso-t" d="M28.0 166.5 L171.1 249.1 L246.9 117.7 L103.9 35.1Z" />
      <path className="iso-w" d="M98.0 45.3 L241.0 127.9 L246.9 117.7 L103.9 35.1Z" />
      <path className="iso-d" d="M109.2 47.9 L113.0 50.1 L115.5 45.7 L111.7 43.5Z" />
      <path className="iso-d" d="M117.5 52.7 L121.4 54.9 L123.9 50.5 L120.1 48.3Z" />
      <path className="iso-d" d="M125.9 57.5 L129.7 59.7 L132.2 55.3 L128.4 53.1Z" />
      <path className="iso-t" d="M96.4 75.5 L203.7 137.5 L207.9 130.2 L100.6 68.2Z" />
      <path className="iso-t" d="M89.7 87.2 L149.3 121.6 L153.5 114.3 L93.9 79.9Z" />
      <path className="iso-y" d="M48.4 158.8 L88.9 182.2 L104.1 155.9 L63.5 132.5Z" />
    </svg>
  );
}

export function IsoMarketing({ className }) {
  return (
    <svg className={className} viewBox="0 0 280 280" width="140" height="140" aria-hidden="true" focusable="false">
      <path className="iso-l" d="M58.3 239.1 L75.0 248.7 L75.0 206.8 L58.3 197.1Z" />
      <path className="iso-r" d="M91.8 239.1 L75.0 248.7 L75.0 206.8 L91.8 197.1Z" />
      <path className="iso-t" d="M75.0 187.5 L91.8 197.1 L75.0 206.8 L58.3 197.1Z" />
      <path className="iso-r" d="M28.0 185.0 L28.3 182.5 L28.8 180.0 L29.5 177.7 L30.6 175.5 L31.8 173.5 L33.2 171.8 L34.8 170.3 L36.6 169.1 L38.5 168.2 L40.5 167.6 L42.5 167.3 L71.5 164.8 L73.5 164.9 L75.6 165.3 L77.5 166.0 L79.4 167.1 L81.2 168.5 L82.8 170.1 L84.3 172.0 L85.5 174.1 L86.6 176.4 L87.3 178.8 L87.9 181.3 L88.2 183.9 L88.2 186.5 L87.9 189.0 L87.4 191.5 L86.6 193.8 L85.6 196.0 L84.4 198.0 L83.0 199.8 L81.3 201.2 L79.6 202.5 L77.7 203.3 L75.7 203.9 L73.7 204.2 L44.7 206.8 L42.6 206.7 L40.6 206.2 L38.6 205.5 L36.8 204.4 L35.0 203.0 L33.4 201.4 L31.9 199.5 L30.7 197.4 L29.6 195.1 L28.8 192.7 L28.3 190.2 L28.0 187.6Z" />
      <path className="iso-t" d="M53.9 182.0 L54.2 179.0 L54.8 176.0 L55.8 173.2 L57.0 170.6 L58.4 168.2 L60.2 166.1 L62.1 164.3 L121.6 113.3 L128.3 108.8 L135.4 105.3 L142.9 103.2 L150.6 102.2 L158.4 102.6 L166.1 104.2 L173.6 107.1 L180.8 111.2 L187.5 116.4 L193.7 122.7 L199.2 129.8 L203.9 137.8 L207.9 146.5 L210.9 155.7 L212.9 165.2 L214.0 175.0 L214.0 184.8 L213.0 194.4 L211.1 203.8 L208.1 212.7 L204.3 221.0 L199.6 228.6 L194.2 235.2 L188.0 240.9 L181.3 245.5 L174.2 248.9 L166.7 251.1 L159.0 252.0 L151.3 251.6 L143.6 250.0 L136.1 247.1 L128.9 243.0 L64.4 205.3 L62.3 203.6 L60.3 201.7 L58.6 199.4 L57.1 196.9 L55.8 194.1 L54.9 191.2 L54.2 188.2 L53.9 185.1Z" />
      <path className="iso-arc" d="M95.8 218.3 L93.9 218.4 L92.1 218.4 L90.2 218.3 L88.4 217.9 L86.6 217.5 L84.8 216.9 L83.0 216.1 L81.3 215.2 L79.6 214.2 L77.9 213.0 L76.4 211.7 L74.8 210.2 L73.4 208.7 L72.1 207.0 L70.8 205.3 L69.6 203.4 L68.5 201.5 L67.5 199.4 L66.6 197.3 L66.6 197.3 L65.9 195.2 L65.2 193.0 L64.7 190.7 L64.2 188.4 L63.9 186.1 L63.7 183.8 L63.7 181.4 L63.7 179.1 L63.9 176.8 L64.2 174.5 L64.6 172.2 L65.1 170.0 L65.8 167.9 L66.5 165.8 L67.4 163.7 L68.3 161.8 L69.4 160.0 L70.6 158.2 L71.8 156.6 L73.2 155.0 L74.6 153.6 L76.1 152.3 L77.7 151.2 L79.3 150.1 L81.0 149.3 L82.7 148.5 L84.5 147.9 L86.3 147.5 L88.1 147.2" />
      <path className="iso-t" d="M101.8 207.7 L98.8 198.6 L96.7 189.0 L95.6 179.3 L95.6 169.5 L96.6 159.8 L98.5 150.4 L101.5 141.5 L105.3 133.2 L110.0 125.7 L115.5 119.0 L121.6 113.3 L128.3 108.8 L135.4 105.3 L142.9 103.2 L150.6 102.2 L158.4 102.6 L166.1 104.2 L173.6 107.1 L180.8 111.2 L187.5 116.4 L193.7 122.7 L199.2 129.8 L203.9 137.8 L207.9 146.5 L210.9 155.7 L212.9 165.2 L214.0 175.0 L214.0 184.8 L213.0 194.4 L211.1 203.8 L208.1 212.7 L204.3 221.0 L199.6 228.6 L194.2 235.2 L188.0 240.9 L181.3 245.5 L174.2 248.9 L166.7 251.1 L159.0 252.0 L151.3 251.6 L143.6 250.0 L136.1 247.1 L128.9 243.0 L122.1 237.8 L115.9 231.6 L110.4 224.4 L105.7 216.4Z" />
      <path className="iso-l" d="M112.9 201.3 L110.6 194.0 L108.9 186.5 L108.1 178.8 L108.1 171.1 L108.8 163.4 L110.4 156.1 L112.7 149.0 L115.7 142.5 L119.4 136.5 L123.7 131.2 L128.6 126.8 L133.9 123.1 L139.5 120.5 L145.4 118.7 L151.5 118.0 L157.6 118.3 L163.7 119.6 L169.6 121.9 L175.3 125.1 L180.6 129.2 L185.5 134.1 L189.8 139.8 L193.6 146.1 L196.7 152.9 L199.1 160.2 L200.7 167.7 L201.5 175.4 L201.6 183.2 L200.8 190.8 L199.2 198.2 L196.9 205.2 L193.9 211.8 L190.2 217.7 L185.9 223.0 L181.0 227.5 L175.8 231.1 L170.1 233.8 L164.2 235.5 L158.1 236.2 L152.0 235.9 L145.9 234.7 L140.0 232.4 L134.3 229.2 L129.0 225.0 L124.1 220.1 L119.8 214.4 L116.0 208.1Z" />
      <path className="iso-arc" d="M224.2 208.8 L223.9 205.2 L223.4 201.6 L222.8 197.9 L222.0 194.3 L221.2 190.5 L220.2 186.8 L219.2 183.0 L218.0 179.3 L216.7 175.5 L215.3 171.7 L213.7 168.0 L212.1 164.2 L210.4 160.5 L208.6 156.8 L206.7 153.1 L204.7 149.5 L202.6 145.9 L200.4 142.4 L198.2 139.0 L195.8 135.6" />
      <path className="iso-arc iso-arc--y" d="M238.1 215.1 L237.7 210.8 L237.1 206.5 L236.4 202.1 L235.5 197.7 L234.5 193.2 L233.3 188.7 L232.0 184.2 L230.6 179.7 L229.0 175.2 L227.4 170.6 L225.5 166.1 L223.6 161.6 L221.5 157.2 L219.4 152.7 L217.1 148.3 L214.7 144.0 L212.2 139.7 L209.5 135.5 L206.8 131.4 L204.0 127.3" />
      <path className="iso-arc" d="M252.0 221.4 L251.5 216.4 L250.8 211.4 L250.0 206.3 L248.9 201.1 L247.8 195.9 L246.4 190.7 L244.9 185.4 L243.2 180.1 L241.4 174.8 L239.4 169.6 L237.3 164.3 L235.1 159.0 L232.7 153.8 L230.1 148.7 L227.4 143.5 L224.6 138.5 L221.7 133.5 L218.7 128.6 L215.5 123.7 L212.3 119.0" />
    </svg>
  );
}

export function IsoAutomation({ className }) {
  return (
    <svg className={className} viewBox="0 0 280 280" width="140" height="140" aria-hidden="true" focusable="false">
      <path className="iso-l" d="M28.0 149.9 L75.2 177.1 L75.2 122.7 L28.0 95.4Z" />
      <path className="iso-r" d="M122.3 149.9 L75.2 177.1 L75.2 122.7 L122.3 95.4Z" />
      <path className="iso-t" d="M75.2 68.2 L122.3 95.4 L75.2 122.7 L28.0 95.4Z" />
      <path className="iso-arc" d="M98.7 109.1 L116.4 119.3" />
      <circle className="iso-dot" cx="98.7" cy="109.1" r="3" />
      <circle className="iso-dot" cx="116.4" cy="119.3" r="3" />
      <path className="iso-l" d="M92.8 187.3 L140.0 214.6 L140.0 160.1 L92.8 132.9Z" />
      <path className="iso-r" d="M187.2 187.3 L140.0 214.6 L140.0 160.1 L187.2 132.9Z" />
      <path className="iso-t" d="M140.0 105.7 L187.2 132.9 L140.0 160.1 L92.8 132.9Z" />
      <path className="iso-arc" d="M163.6 146.5 L181.3 156.7" />
      <circle className="iso-dot" cx="163.6" cy="146.5" r="3" />
      <circle className="iso-dot" cx="181.3" cy="156.7" r="3" />
      <path className="iso-y" d="M157.7 224.8 L204.8 252.0 L204.8 197.5 L157.7 170.3Z" />
      <path className="iso-y" d="M252.0 224.8 L204.8 252.0 L204.8 197.5 L252.0 170.3Z" />
      <path className="iso-y" d="M204.8 143.1 L252.0 170.3 L204.8 197.5 L157.7 170.3Z" />
    </svg>
  );
}
