import React from 'react';

/* THE CARD ILLUSTRATIONS, 2026-09-24 (the founder's illustration pass; the
   isometric outline style of coinsetters.io's services section, translated
   to this palette). They are the card's artwork on home's What we do and
   About's What we build it around.

   TRUE ISOMETRIC, 30 degree axes: a point (x, y, z) lands at
   (x - y) * cos 30, (x + y) * sin 30 - z. The geometry is generated, not
   hand-placed, so the light is the same on all four: TOP lit-raised, LEFT
   lit-near, RIGHT steel-dark. The keyline is bone at 1.5px with round joins,
   the sound arcs and connectors 2px (ArtCard.css).

   THE SECOND ITERATION, later on 2026-09-24 (the founder): the objects float
   - no base plates, no shadows - and each is scaled so its larger dimension
   fills 124px of the 140px slot, centred. Each has exactly one yellow
   element:

     Branding     a stamp block with a raised V on its top face (kept); the V
     Websites     a browser lying flat like a tablet, 3:2, three dots, a wide
                  bar, a narrow bar; the block
     Marketing    a megaphone, a small cylinder widening to an open elliptical
                  mouth, angled 30 degrees up the iso axis, the handle under
                  it, three sound arcs; the middle arc
     Automation   three 32-unit cubes on the iso axis with 12-unit gaps,
                  joined along their top edges by connectors with a dot at
                  each join; the last cube

   THE THIRD ITERATION, 2026-09-24 (the founder's energy pass): the cards
   are cream now, so the palette is the light one - an asphalt keyline at
   1.5px, TOP white, LEFT cream, RIGHT bone - and each object carries one
   arc blue element beside its yellow one:

     Branding     the yellow V; a blue base edge (an 8-unit slab under the block)
     Websites     the yellow block; the blue top bar, its three dots white
     Marketing    the yellow middle arc; a blue band round the horn
     Automation   the yellow last cube; the blue connectors and their dots

   Arc blue appears here and on the Plan Builder's progress dots, nowhere
   else. Generated by iso3.py (the scratchpad of that session).

   NORMALISED, 2026-09-24 (the founder's final details): each object is
   exactly 112px tall in the 140 x 140 art box, centred horizontally, its
   lowest point on one baseline 14px above the box floor, the same on home
   and About. Rendered widths: Branding 136.8px, Websites 179.6px,
   Marketing 149.7px, Automation 136.5px. The two wider than the box
   overflow it evenly on both sides (`overflow="visible"`), Websites by
   19.8px and Marketing by 4.8px each side, rather than being clipped.
   Generated by iso4.py.

   Decorative: the card's title says what each one is. */

export function IsoBranding({ className }) {
  return (
    <svg className={className} viewBox="0 0 280 280" width="140" height="140" overflow="visible" aria-hidden="true" focusable="false">
      <path className="iso-b" d="M3.2 173.0 L140.0 252.0 L140.0 240.5 L3.2 161.5Z" />
      <path className="iso-b" d="M276.8 173.0 L140.0 252.0 L140.0 240.5 L276.8 161.5Z" />
      <path className="iso-b" d="M140.0 82.6 L276.8 161.5 L140.0 240.5 L3.2 161.5Z" />
      <path className="iso-l" d="M3.2 161.5 L140.0 240.5 L140.0 185.9 L3.2 107.0Z" />
      <path className="iso-r" d="M276.8 161.5 L140.0 240.5 L140.0 185.9 L276.8 107.0Z" />
      <path className="iso-t" d="M140.0 28.0 L276.8 107.0 L140.0 185.9 L3.2 107.0Z" />
      <path className="iso-l" d="M111.4 136.4 L89.0 123.5 L89.0 110.6 L111.4 123.5Z" />
      <path className="iso-r" d="M219.6 109.8 L111.4 136.4 L111.4 123.5 L219.6 96.9Z" />
      <path className="iso-l" d="M89.0 123.5 L135.0 61.0 L135.0 48.1 L89.0 110.6Z" />
      <path className="iso-y" d="M135.0 48.1 L157.4 61.0 L130.1 99.8 L197.2 84.0 L219.6 96.9 L111.4 123.5 L89.0 110.6Z" />
    </svg>
  );
}

export function IsoWebsites({ className }) {
  return (
    <svg className={className} viewBox="0 0 280 280" width="140" height="140" overflow="visible" aria-hidden="true" focusable="false">
      <path className="iso-l" d="M-39.6 127.6 L175.9 252.0 L175.9 235.4 L-39.6 111.0Z" />
      <path className="iso-r" d="M319.6 169.0 L175.9 252.0 L175.9 235.4 L319.6 152.4Z" />
      <path className="iso-t" d="M104.1 28.0 L319.6 152.4 L175.9 235.4 L-39.6 111.0Z" />
      <path className="iso-b" d="M104.1 28.0 L319.6 152.4 L294.5 167.0 L78.9 42.5Z" />
      <path className="iso-d" d="M111.3 40.4 L118.4 44.6 L107.7 50.8 L100.5 46.7Z" />
      <path className="iso-d" d="M125.6 48.7 L132.8 52.9 L122.0 59.1 L114.9 55.0Z" />
      <path className="iso-d" d="M140.0 57.0 L147.2 61.2 L136.4 67.4 L129.2 63.3Z" />
      <path className="iso-t" d="M82.5 61.2 L244.2 154.5 L233.4 160.7 L71.7 67.4Z" />
      <path className="iso-t" d="M61.0 73.6 L150.8 125.5 L140.0 131.7 L50.2 79.9Z" />
      <path className="iso-y" d="M35.8 88.1 L114.9 133.8 L75.3 156.6 L-3.7 111.0Z" />
    </svg>
  );
}

export function IsoMarketing({ className }) {
  return (
    <svg className={className} viewBox="0 0 280 280" width="140" height="140" overflow="visible" aria-hidden="true" focusable="false">
      <path className="iso-l" d="M24.6 220.3 L43.7 231.3 L43.7 183.7 L24.6 172.7Z" />
      <path className="iso-r" d="M62.7 220.3 L43.7 231.3 L43.7 183.7 L62.7 172.7Z" />
      <path className="iso-t" d="M43.7 161.7 L62.7 172.7 L43.7 183.7 L24.6 172.7Z" />
      <path className="iso-r" d="M-9.7 159.0 L-9.4 156.1 L-8.9 153.3 L-8.0 150.6 L-6.8 148.1 L-5.4 145.9 L-3.8 143.9 L-2.0 142.2 L0.0 140.8 L2.2 139.8 L4.4 139.1 L6.7 138.9 L39.7 135.9 L42.0 136.0 L44.3 136.5 L46.5 137.4 L48.7 138.6 L50.7 140.2 L52.5 142.0 L54.2 144.2 L55.6 146.6 L56.8 149.2 L57.7 151.9 L58.3 154.8 L58.6 157.7 L58.6 160.6 L58.3 163.5 L57.7 166.3 L56.9 168.9 L55.7 171.4 L54.3 173.7 L52.7 175.7 L50.9 177.4 L48.9 178.7 L46.7 179.8 L44.5 180.4 L42.2 180.7 L9.2 183.6 L6.9 183.5 L4.6 183.0 L2.4 182.2 L0.2 181.0 L-1.8 179.4 L-3.7 177.5 L-5.3 175.4 L-6.7 173.0 L-7.9 170.4 L-8.8 167.7 L-9.4 164.8 L-9.7 161.9Z" />
      <path className="iso-l" d="M19.7 155.6 L20.0 152.1 L20.7 148.7 L21.8 145.5 L23.2 142.6 L24.9 139.9 L26.8 137.5 L29.0 135.4 L96.6 77.5 L104.2 72.3 L112.3 68.4 L120.8 65.9 L129.5 64.9 L138.4 65.3 L147.1 67.2 L155.6 70.4 L163.8 75.1 L171.4 81.0 L178.5 88.1 L184.7 96.3 L190.1 105.3 L194.6 115.2 L198.0 125.6 L200.3 136.5 L201.5 147.5 L201.6 158.7 L200.5 169.6 L198.2 180.3 L194.9 190.4 L190.6 199.8 L185.2 208.4 L179.0 216.0 L172.1 222.4 L164.5 227.6 L156.3 231.5 L147.8 234.0 L139.1 235.0 L130.3 234.6 L121.5 232.8 L113.0 229.5 L104.9 224.8 L31.6 182.0 L29.2 180.1 L27.0 177.8 L25.0 175.3 L23.3 172.4 L21.9 169.3 L20.8 166.0 L20.1 162.6 L19.7 159.1Z" />
      <path className="iso-b" d="M25.6 153.3 L26.1 148.6 L27.0 144.0 L28.5 139.6 L30.4 135.5 L32.7 131.8 L35.3 128.6 L38.4 125.8 L44.3 120.7 L48.1 118.1 L52.1 116.2 L56.2 115.0 L60.5 114.4 L64.9 114.6 L69.2 115.6 L73.4 117.2 L77.4 119.5 L81.2 122.4 L84.6 125.9 L87.7 129.9 L90.4 134.4 L92.6 139.2 L94.3 144.3 L95.4 149.7 L96.0 155.2 L96.0 160.6 L95.5 166.0 L94.4 171.3 L92.7 176.3 L90.6 180.9 L88.0 185.1 L84.9 188.9 L81.5 192.0 L77.7 194.6 L73.7 196.5 L69.6 197.7 L65.3 198.2 L60.9 198.0 L56.6 197.1 L52.4 195.5 L48.4 193.2 L41.9 189.4 L38.6 186.9 L35.6 183.8 L32.9 180.3 L30.5 176.4 L28.6 172.1 L27.1 167.6 L26.1 162.9 L25.6 158.1Z" />
      <path className="iso-t" d="M74.1 184.8 L70.6 174.3 L68.3 163.5 L67.1 152.4 L67.1 141.3 L68.2 130.3 L70.4 119.7 L73.7 109.5 L78.1 100.1 L83.4 91.5 L89.6 84.0 L96.6 77.5 L104.2 72.3 L112.3 68.4 L120.8 65.9 L129.5 64.9 L138.4 65.3 L147.1 67.2 L155.6 70.4 L163.8 75.1 L171.4 81.0 L178.5 88.1 L184.7 96.3 L190.1 105.3 L194.6 115.2 L198.0 125.6 L200.3 136.5 L201.5 147.5 L201.6 158.7 L200.5 169.6 L198.2 180.3 L194.9 190.4 L190.6 199.8 L185.2 208.4 L179.0 216.0 L172.1 222.4 L164.5 227.6 L156.3 231.5 L147.8 234.0 L139.1 235.0 L130.3 234.6 L121.5 232.8 L113.0 229.5 L104.9 224.8 L97.2 218.9 L90.2 211.8 L83.9 203.7 L78.5 194.6Z" />
      <path className="iso-l" d="M86.7 177.4 L84.0 169.2 L82.2 160.6 L81.3 151.9 L81.2 143.1 L82.1 134.4 L83.9 126.0 L86.5 118.0 L89.9 110.6 L94.1 103.8 L99.0 97.9 L104.5 92.8 L110.5 88.7 L116.9 85.6 L123.7 83.6 L130.6 82.8 L137.5 83.1 L144.4 84.6 L151.1 87.2 L157.6 90.8 L163.6 95.5 L169.2 101.1 L174.1 107.6 L178.4 114.7 L181.9 122.5 L184.6 130.7 L186.4 139.3 L187.4 148.1 L187.4 156.8 L186.6 165.5 L184.8 173.9 L182.2 181.9 L178.7 189.3 L174.5 196.1 L169.6 202.1 L164.1 207.2 L158.1 211.3 L151.7 214.3 L145.0 216.3 L138.1 217.1 L131.1 216.8 L124.2 215.3 L117.5 212.7 L111.1 209.1 L105.0 204.4 L99.5 198.8 L94.5 192.4 L90.3 185.2Z" />
      <path className="iso-arc" d="M238.7 218.7 L239.0 211.7 L238.9 204.4 L238.4 197.0 L237.5 189.4 L236.3 181.7 L234.7 173.8 L232.8 165.9 L230.5 157.9 L227.9 149.9 L225.0 141.9 L221.7 133.9 L218.1 126.0 L214.3 118.1 L210.1 110.4 L205.7 102.8 L201.0 95.4 L196.1 88.1 L191.0 81.1 L185.7 74.3 L180.2 67.8" />
      <path className="iso-arc iso-arc--y" d="M264.1 235.3 L264.4 226.6 L264.2 217.6 L263.6 208.4 L262.5 199.0 L261.0 189.3 L259.1 179.6 L256.7 169.7 L253.9 159.8 L250.6 149.9 L246.9 139.9 L242.9 130.0 L238.5 120.1 L233.7 110.4 L228.5 100.8 L223.0 91.3 L217.2 82.1 L211.1 73.1 L204.8 64.4 L198.2 56.0 L191.3 47.9" />
      <path className="iso-arc" d="M289.4 252.0 L289.7 241.6 L289.6 230.8 L288.8 219.8 L287.6 208.5 L285.8 197.0 L283.4 185.4 L280.6 173.6 L277.2 161.7 L273.3 149.8 L268.9 137.9 L264.1 126.1 L258.8 114.3 L253.0 102.7 L246.9 91.2 L240.3 79.9 L233.4 68.9 L226.1 58.1 L218.5 47.7 L210.6 37.7 L202.5 28.0" />
    </svg>
  );
}

export function IsoAutomation({ className }) {
  return (
    <svg className={className} viewBox="0 0 280 280" width="140" height="140" overflow="visible" aria-hidden="true" focusable="false">
      <path className="iso-l" d="M3.5 127.6 L61.0 160.7 L61.0 94.4 L3.5 61.2Z" />
      <path className="iso-r" d="M118.4 127.6 L61.0 160.7 L61.0 94.4 L118.4 61.2Z" />
      <path className="iso-t" d="M61.0 28.0 L118.4 61.2 L61.0 94.4 L3.5 61.2Z" />
      <path className="iso-arc iso-arc--b" d="M89.7 77.8 L111.3 90.2" />
      <circle className="iso-dot" cx="89.7" cy="77.8" r="3" />
      <circle className="iso-dot" cx="111.3" cy="90.2" r="3" />
      <path className="iso-l" d="M82.5 173.2 L140.0 206.4 L140.0 140.0 L82.5 106.8Z" />
      <path className="iso-r" d="M197.5 173.2 L140.0 206.4 L140.0 140.0 L197.5 106.8Z" />
      <path className="iso-t" d="M140.0 73.6 L197.5 106.8 L140.0 140.0 L82.5 106.8Z" />
      <path className="iso-arc iso-arc--b" d="M168.7 123.4 L190.3 135.9" />
      <circle className="iso-dot" cx="168.7" cy="123.4" r="3" />
      <circle className="iso-dot" cx="190.3" cy="135.9" r="3" />
      <path className="iso-y" d="M161.6 218.8 L219.0 252.0 L219.0 185.6 L161.6 152.4Z" />
      <path className="iso-y" d="M276.5 218.8 L219.0 252.0 L219.0 185.6 L276.5 152.4Z" />
      <path className="iso-y" d="M219.0 119.3 L276.5 152.4 L219.0 185.6 L161.6 152.4Z" />
    </svg>
  );
}
