import React from 'react';
import { useReveal } from '../home/hooks.js';
import { OriginAds, OriginPage, OriginSystem } from './OriginScenes.jsx';
import './story.css';

/* WHERE WE COME FROM (the storytelling pass, 2026-10-01; drawn
   2026-10-02, the founder's five fixes). Three stops, each with its own
   isometric scene on a cream tile, 16px radius: 01 one ad panel alone, 02
   the ad beside a page with a form, 03 four tiles joined, the fourth
   yellow. The scenes are in the card illustrations' hand, in its light
   palette (OriginScenes.jsx). Under each tile the stop's numeral, title and
   line (VEXELTECH-COPY.md V3.1, About, Where we come from).

   The tiles build in once when the row comes into view, 100ms apart, on
   the reveal curve (opacity and transform only). Reduced motion: still. */
const STOPS = [
  {
    n: '01',
    t: 'The ads.',
    d: 'We started as a paid media team running Google and Meta campaigns for small businesses. Most of the spend died on the page after the click.',
  },
  {
    n: '02',
    t: 'The build.',
    d: 'So we built the pages, then the whole site, then the follow-up that runs after the call.',
  },
  {
    n: '03',
    t: 'The whole thing.',
    d: "VexelTech, 2026. Branding, website, marketing and automation from one team at flat prices, for businesses that can't carry four vendors.",
  },
];

/* DRAWN, 2026-10-02 (the founder's five fixes): the typographic diagram
   came off; each stop has an isometric scene of its own on a cream tile
   (OriginScenes.jsx, generated by .measure/iso-origin.py). */
const SCENES = [OriginAds, OriginPage, OriginSystem];

export default function GrowthDiagram() {
  const [ref, revealed] = useReveal();
  return (
    <section className="vt st-sec st--light gd" aria-labelledby="gd-h">
      <div className="st-in">
        <h2 className="st-h" id="gd-h">
          Where we come from
        </h2>
        <ol className="gd__stops" ref={ref} data-revealed={revealed ? 'true' : 'false'}>
          {STOPS.map(({ n, t, d }, k) => {
            const Scene = SCENES[k];
            return (
              <li className="gd__stop" key={n}>
                <div className="gd__tile st-rv" style={{ '--i': k }}>
                  <Scene className="gd__scene" />
                </div>
                <p className="gd__n st-mono">{n}</p>
                <h3 className="gd__t">{t}</h3>
                <p className="gd__d st-soft">{d}</p>
              </li>
            );
          })}
        </ol>
      </div>
    </section>
  );
}
