import React from 'react';

/* WHERE WE COME FROM, DRAWN (the founder's five fixes, 2026-10-02). Three
   new isometric scenes in the hand of the card illustrations
   (Illustrations.jsx): true isometric on 30 degree axes, an asphalt 1.5px
   keyline with round joins, faces TOP white, LEFT cream, RIGHT bone (the
   light palette, on a cream tile), connectors 2px with an asphalt dot at
   each join, each fitted to 112px with its foot on the shared baseline 14px
   above the floor. GENERATED by .measure/iso-origin.py; change the script,
   not this file.

     OriginAds     01: one ad panel standing alone, an image block and a
                   button on its face
     OriginPage    02: the ad panel beside a page with a header, two form
                   fields and a button
     OriginSystem  03: four flat tiles joined by connectors, the fourth
                   (the front one) yellow, the scene's one yellow

   Decorative: each stop's title says what the scene is. */

export function OriginAds({ className }) {
  return (
    <svg className={className} viewBox="0 0 280 280" width="140" height="140" aria-hidden="true" focusable="false">
      <path className="iso-l" d="M80.7 192.8 L183.3 252.0 L183.3 96.5 L80.7 37.3Z" />
      <path className="iso-r" d="M199.3 242.7 L183.3 252.0 L183.3 96.5 L199.3 87.2Z" />
      <path className="iso-t" d="M96.7 28.0 L199.3 87.2 L183.3 96.5 L80.7 37.3Z" />
      <path className="iso-t" d="M93.5 137.2 L170.5 181.7 L170.5 103.9 L93.5 59.5Z" />
      <path className="iso-d" d="M93.5 178.0 L138.4 203.9 L138.4 181.7 L93.5 155.7Z" />
    </svg>
  );
}

export function OriginPage({ className }) {
  return (
    <svg className={className} viewBox="0 0 280 280" width="140" height="140" aria-hidden="true" focusable="false">
      <path className="iso-l" d="M40.2 143.2 L112.0 184.7 L112.0 75.9 L40.2 34.5Z" />
      <path className="iso-r" d="M123.2 178.2 L112.0 184.7 L112.0 75.9 L123.2 69.4Z" />
      <path className="iso-t" d="M51.4 28.0 L123.2 69.4 L112.0 75.9 L40.2 34.5Z" />
      <path className="iso-t" d="M49.2 104.4 L103.0 135.5 L103.0 81.1 L49.2 50.0Z" />
      <path className="iso-d" d="M49.2 132.9 L80.6 151.0 L80.6 135.5 L49.2 117.3Z" />
      <path className="iso-l" d="M147.8 205.4 L228.6 252.0 L228.6 117.3 L147.8 70.7Z" />
      <path className="iso-r" d="M239.8 245.5 L228.6 252.0 L228.6 117.3 L239.8 110.9Z" />
      <path className="iso-t" d="M159.1 64.3 L239.8 110.9 L228.6 117.3 L147.8 70.7Z" />
      <path className="iso-r" d="M156.8 96.6 L219.6 132.9 L219.6 122.5 L156.8 86.3Z" />
      <path className="iso-t" d="M156.8 130.3 L219.6 166.5 L219.6 148.4 L156.8 112.2Z" />
      <path className="iso-t" d="M156.8 156.2 L219.6 192.4 L219.6 174.3 L156.8 138.1Z" />
      <path className="iso-d" d="M156.8 187.3 L192.7 208.0 L192.7 189.8 L156.8 169.1Z" />
    </svg>
  );
}

export function OriginSystem({ className }) {
  return (
    <svg className={className} viewBox="0 0 280 280" width="140" height="140" aria-hidden="true" focusable="false">
      <path className="iso-l" d="M93.3 149.6 L140.0 176.6 L140.0 167.6 L93.3 140.6Z" />
      <path className="iso-r" d="M186.7 149.6 L140.0 176.6 L140.0 167.6 L186.7 140.6Z" />
      <path className="iso-t" d="M140.0 113.7 L186.7 140.6 L140.0 167.6 L93.3 140.6Z" />
      <path className="iso-l" d="M158.7 187.3 L205.3 214.3 L205.3 205.3 L158.7 178.4Z" />
      <path className="iso-r" d="M252.0 187.3 L205.3 214.3 L205.3 205.3 L252.0 178.4Z" />
      <path className="iso-t" d="M205.3 151.4 L252.0 178.4 L205.3 205.3 L158.7 178.4Z" />
      <path className="iso-l" d="M28.0 187.3 L74.7 214.3 L74.7 205.3 L28.0 178.4Z" />
      <path className="iso-r" d="M121.3 187.3 L74.7 214.3 L74.7 205.3 L121.3 178.4Z" />
      <path className="iso-t" d="M74.7 151.4 L121.3 178.4 L74.7 205.3 L28.0 178.4Z" />
      <path className="iso-l" d="M93.3 225.1 L140.0 252.0 L140.0 243.0 L93.3 216.1Z" />
      <path className="iso-r" d="M186.7 225.1 L140.0 252.0 L140.0 243.0 L186.7 216.1Z" />
      <path className="iso-y" d="M140.0 189.1 L186.7 216.1 L140.0 243.0 L93.3 216.1Z" />
      <path className="iso-arc" d="M140.0 140.6 L205.3 178.4" />
      <path className="iso-arc" d="M205.3 178.4 L140.0 216.1" />
      <path className="iso-arc" d="M140.0 216.1 L74.7 178.4" />
      <path className="iso-arc" d="M74.7 178.4 L140.0 140.6" />
      <circle className="iso-dot" cx="140.0" cy="140.6" r="3.6" />
      <circle className="iso-dot" cx="205.3" cy="178.4" r="3.6" />
      <circle className="iso-dot" cx="74.7" cy="178.4" r="3.6" />
      <circle className="iso-dot" cx="140.0" cy="216.1" r="3.6" />
    </svg>
  );
}
